char menurelatorio(void);
void listaclistatus(char);
void listaclitotal(void);
void listacliordemabc(void);
void modulorelatorio(void);
void menurelatorioclientes(void);
char relatorioclientes(void);
void menurelatoriovendas(void);
void menurelatoriofuncionarios(void);
void menurelatorioprodutos(void);
char relatoriovendas(void);
void listaventotal(void);
void listavenstatus(char);
char relatoriofuncionarios(void);
void listafuntotal(void);
void listafunstatus(char);
void listafunordemabc(void);
char relatorioprodutos(void);
void listaprototal(void);
void listaprostatus(char);
void listaproordemabc(void);
char* get_funcionario(const char* cpf);
char* get_venda(const char* cod);